version: '3'
services:
  nginx:
    image: nginx:1.24
    ports:
      - 8081:8081
      - 8082:8082
      - 8083:8083
      - 8084:8084
      - 8086:8086
      - 8087:8087
      - 8088:8088
      - 8089:8089
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html/:/usr/share/nginx/html/
  apache:
    image: httpd:2.4.48
    ports:
      - 5001:80
    volumes:
      - ./apache/public-html/:/usr/local/apache2/htdocs/
      - ./apache/my-httpd.conf:/usr/local/apache2/conf/httpd.conf
  tomcat:
    image: tomcat:10.0.10
    ports:
      - 5002:80
    volumes:
      - ./tomcat/demo.war:/usr/local/tomcat/webapps/demo.war
      - ./tomcat/server.xml:/usr/local/tomcat/conf/server.xml
